
module.exports = {
	
	bbdd: [

		{
			name:'Hoya de Don Gil',
			description:'Murcia',
			lat:38.020588,   
			lng:-1.8195460,
			image:'ui/images/gallery/imagen_ejemplo1.jpg',
			gallery:[
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
				{image:'ui/images/gallery/imagen_ejemplo1.jpg'},
			],
			hitos:[
				{title:'Casa rural', text:'Hito 1', lat:38.020588, lng:-1.8195460, image:'ui/images/f_hito1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Cultivo', text:'Hito 2', lat:38.018847, lng:-1.8231190, image:'ui/images/f_hito2.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Viñedo', text:'Hito 3', lat:38.018795, lng:-1.8262950, image:'ui/images/f_hito3.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Repoblado', text:'Hito 4', lat:38.016495, lng:-1.8283220, image:'ui/images/f_hito4.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Pinar', text:'Hito 5', lat:38.010946, lng:-1.8218960, image:'ui/images/f_hito5.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Almendros', text:'Hito 6', lat:38.016489, lng:-1.8181730, image:'ui/images/f_hito6.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'}
			],
			pois:[
				{title:'Casa rural', text:'Descripción breve del hito', lat:39.505, lng:-0.505, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Cultivo', text:'Descripción breve del hito', lat:39.495, lng:-0.51, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Viñedo', text:'Descripción breve del hito', lat:39.49, lng:-0.51, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Repoblado', text:'Descripción breve del hito', lat:39.51, lng:-0.515, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Pinar', text:'Descripción breve del hito', lat:39.51, lng:-0.49, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'},
				{title:'Almendros', text:'Descripción breve del hito', lat:39.50, lng:-0.485, image:'ui/images/gallery/imagen_ejemplo1.jpg', longtext:'El inicio de nuestra ruta comienza en la casa rural “Hoya de don Gil”. Su nombre, como el de otros parajes de este entorno, se relaciona con el paisaje de este paso entre montañas, las Sierra de Burete y del Quípar. Como curiosidad comentar que esta casa fue una de las primeras casas rurales que existieron en la Región de Murcia.\r\rUna “hoya” es una concavidad u hondura grande formada en la tierra. Como podéis observar mirando a vuestro alrededor podemos ver que estamos rodeados de unos altos picos estando la casa de la Hoya de don Gil justo en el centro, dándole a la zona esa forma de hoya o cuenco. Esta forma orográfica hace que el agua caída en las lluvias se encamine al centro de la hoya haciendo de estas unas tierras fértiles y aptas para el cultivo de frutales, viñedo y cereal.\r\rFrente a la casa rural podemos observar cultivos de cereales que dependiendo de la época del año en que visitemos la finca pueden estar cultivado o no.'}
			],
		},
		/*
		{
			name:'Finca 2',
			description:'Descripción de la finca 1',
			lat:39.5,
			lng:-1.5,
			image:'ui/images/gallery/imagen_ejemplo1.jpg'
		},
		
		{
			name:'Finca 3',
			description:'Descripción de la finca 1',
			lat:40,
			lng:-2.5,
			image:'ui/images/gallery/imagen_ejemplo1.jpg'
		},
		
		{
			name:'Finca 4',
			description:'Descripción de la finca 1',
			lat:38,
			lng:-2,
			image:'ui/images/gallery/imagen_ejemplo1.jpg'
		}
		*/
	]
	
}
